### PR TITLE
UX: Messages: Use "Newest" as default mode

### LINKED ISSUE #570: UX: Messages: Use "Newest" as default mode
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Most of the time, we have experienced that users want to see the newest first

### Describe the feature you're interested in

In here:

https://github.com/kafbat/kafka-ui/blob/3f3ca4cfabe36acd57fddcec1589c39a1800f61f/frontend/src/lib/hooks/useMessagesFilters.ts#L38

Use default 1, which would be `latest`

### Describe alternatives you've considered

Making it a configuration parameter, but I think "Newest" is good enough. I'd like to check here if everyone also agrees that Newest as default would be the best default. 

### Version you're running

1.0.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by polegkashti**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Simply chaned the default filter mode.

**Is there anything you'd like reviewers to focus on?**
Hi, I’ve noticed that other users have also expressed a need for this change, and some of our Kafka users specifically mentioned it. I believe it’s a great idea to modify the default mode, as it aligns better with Kafka's real-time streaming nature.

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [x] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**
gamer cat

### CODE REVIEW

**Comment by polegkashti** [comment]
resolves #570

**Review by Haarolean — APPROVED** [review]

**Comment by fallen-up** [comment]
i tried to solve the problem this way. as a result, sometimes "Newest" is displayed in the UI, but the messages are empty. only changing to "Oldest" and then back to "Newest" helps.

**Comment by Haarolean** [comment]
> i tried to solve the problem this way. as a result "Newest" is displayed in the UI, but sometimes the messages are empty. only changing to "Oldest" and then back to "Newest" helps.

should be working, as we have `const defaultModeValue = ModeOptions[0].value;` in `useMEssageFilters.ts`. @polegkashti can you confirm?

**Comment by polegkashti** [comment]
> > i tried to solve the problem this way. as a result "Newest" is displayed in the UI, but sometimes the messages are empty. only changing to "Oldest" and then back to "Newest" helps.
> 
> should be working, as we have `const defaultModeValue = ModeOptions[0].value;` in `useMEssageFilters.ts`. @polegkashti can you confirm?

Based on my testing, everything is functioning properly, and I don't see any reason for this issue to occur.

**Comment by polegkashti** [comment]
I tested the change again with a variety of messages and was unable to reproduce the issue. Additionally, I reviewed the codebase for any other references to the "Newest" filter and found no related components.

Given this, I believe there isn't a valid reason to withhold approval for this pull request. If the issue continues to affect you, I recommend opening a new issue with more details to help us investigate further :)

**Comment by Haarolean** [comment]
@polegkashti thank you!

**Pull request merged**
