### PR TITLE
BE: Chore: Bump Spring Boot w/ dependencies

### PR DESCRIPTION
**Pull request by sixdouglas**
Bump several frameworks versions

- [?] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

I don't know why yet, but make this `PropertyResolverImplTest` test pass, I needed to change the `CustomPropertiesClass` to a `record`! I'm still looking on this issue, though the functionality of mapping properties to custom classes is not used in the `kafka-ui` project.

I also had to change a little something in the `KsqlApiClientTest` test since Jackson now return DoubleNode instead of DecimalNode. Don't know why either. 

I let you decide if these differences are breaking changes.

**What changes did you make?** (Give an overview)

Bump framework versions

- mapstruct : 1.5.5.Final -> 1.6.2
- lombok : 1.18.32 -> 1.18.34
- snakeyaml : 2.2 -> 2.3
- spring-boot : 3.1.9 -> 3.3.4
- json : 20231013 -> 20240303
- guava : 33.0.0-jre -> 33.3.1-jre

- junit : 5.9.1 -> 5.11.2
- testcontainers : 1.19.5 -> 1.20.2

**Is there anything you'd like reviewers to focus on?**

All unit tests are OK on my machine, but the smoke tests from the `prod` profile are not. They are failing with this error:

```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:8080
Caused by: java.net.ConnectException: Connection refused
``` 

I followed the Build and Run with Docker tutorial, the app works locally! I can navigate and see the topics, their characteristics and their content without any issues in the logs as in the UI.

@Haarolean maybe you help me figure out what happens or at least give me some hints on where to look for details? 

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ ] Manually (please, describe, if necessary)
- [x] Unit checks
- [ ] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sixdouglas** [comment]
This PR can help #490 issue

**Comment by sixdouglas** [comment]
It looks like I didn't start the `docker compose` before running the smoke-tests. 
This explains the `Connection refused` error I got.
Now I have the `Container compose-kafka-connect0-1` that fails to start.
Still work in progress

**Comment by Haarolean** [comment]
> It looks like I didn't start the `docker compose` before running the smoke-tests. This explains the `Connection refused` error I got. Now I have the `Container compose-kafka-connect0-1` that fails to start. Still work in progress

I've run the tests here, in CI, nothing (new) fails. 
Can you please run trivy on your branch so we can take a look if removing deps overrides introduced new CVEs?

**Comment by sixdouglas** [comment]
the trivy report still looks good 

[trivy.json](https://github.com/user-attachments/files/17368431/trivy.json)

**Review by Haarolean — APPROVED** [review]

**Comment by Haarolean** [comment]
@sixdouglas thank you for your first contribution to kafbat UI!

**Pull request merged**
