### PR TITLE
Docs: Update zookeeper image

### PR DESCRIPTION
**Pull request by polegkashti**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)
Just a small change that allowed me to run the docker compose file while developing. I got this error when running `docker compose`
ui-acl-with-zk.yaml: `version` is obsolete

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [ ] No need to
- [ X] Manually (please, describe, if necessary)
- [ ] Unit checks
- [ ] Integration checks
- [ ] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [X ] My changes generate no new warnings (e.g. Sonar is happy)
- [X ] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [X ] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

### CODE REVIEW

**Comment by Haarolean** [comment]
>ui-acl-with-zk.yaml: version is obsolete
This is related to the file header (`version: '2'`) which is no longer needed in new compose versions. Can you elaborate how is the change related to this warning?

**Comment by polegkashti** [comment]
Hey, there. 
Sorry so this is the actual issue when trying to use to docker compose file:
`ERROR: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release.` 
After some reading I found this in the official documentation of docker: 

> These legacy formats should no longer be used, and users are recommended to update images to use current formats, or to upgrade to more current images. Starting with Docker v26.0, pulling these images is disabled by default, and produces an error when attempting to pull the image.

So I changed the image to more updated one and it seems to fix the issue.

**Comment by Haarolean** [comment]
Ok, I see. Can we pin the version, please? Like it is done for all other images. Feel free to pick any compatible one.

**Comment by polegkashti** [comment]
I added the latest stable version stable version of zookeeper (3.8) according to the official documentation and tested it.

**Review by Haarolean — APPROVED** [review]

**Comment by Haarolean** [comment]
@polegkashti thank you!

**Pull request merged**
