### PR TITLE
BE: Chore: Upgrade java to 21

### LINKED ISSUE #490: Upgrade to Java 21
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

No

### Describe the feature you're interested in

As Java 21 is the [latest LTS version](https://endoflife.date/oracle-jdk), I think that we should start testing(and releasing) the project using Java 21

### Describe alternatives you've considered

Using Multi-stage builds is an option but it puts me at risk of unknowns as the project is currently tested using Java 17. 

### Version you're running

2956664

### Additional context

We are currently using Java 17  

https://github.com/kafbat/kafka-ui/blob/8c7012679d7ec0293e0f96a1740690bf0bfc994e/pom.xml#L21

### PR DESCRIPTION
**Pull request by sixdouglas**
Resolves #490
bump java version to 21

- kafka client: 3.3.1 -> 3.8.0
- aspectj: 1.9.9.1 -> 1.9.21

Maven Plugins:
- clean: 3.2.0 -> 3.4.0
- compile: 3.10.1 -> 3.13.0
- resources: 3.2.0 -> 3.3.1
- surefire: 3.1.2 -> 3.5.1
- openapi generator : 6.6.0 -> 7.9.0
- springdoc openapi webflux: 1.2.32 -> 1.8.0
- surefire: 3.2.3 -> 3.5.1 (for e2e tests)
- surefire-ng: 3.2.5 -> 3.5.1 (for e2e tests)

- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [X] No need to
- [X] Manually (please, describe, if necessary)
- [X] Unit checks
- [X] Integration checks
- [X] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [X] My changes generate no new warnings (e.g. Sonar is happy)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by sixdouglas** [comment]
Hi @Haarolean,

Here is another PR to bump versions of several components, trying to go to Java 21 another step to #490.

I still haven't been able to run the smoke, regression or sanity tests on my Mac M1. I've managed to solve some issues around docker incompatibilities like `kdsqldb`or the `create-connectors` images in the `documentation/compose/e2e-tests.yaml` file.

**Comment by Haarolean** [comment]
Yeah I remember having issues with running e2e on m1 as well, mostly due to x86-based images in e2e compose. As an alternative, you can run them in your forked repo.

**Comment by sixdouglas** [comment]
The build is failing, it seems that it uses the version of the scripts on the main branch and not the updated ones in the PR. 
Screenshot 2024-10-19 at 21 00 54
Screenshot 2024-10-19 at 21 01 16

**Comment by sixdouglas** [comment]
> As an alternative, you can run them in your forked repo.

I didn't know I could do that, do you have a link to explain it?

**Comment by sixdouglas** [comment]
I still can't make the e2e tests work locally.
But I was able to reproduce and fix the exception raised in the smoke tests you run.

**Comment by Haarolean** [comment]
> > As an alternative, you can run them in your forked repo.
> 
> I didn't know I could do that, do you have a link to explain it?

sorry I don't have any articles on this, the point is that you can fork the repo and run whatever changes you need even on modified workflows in the fork repo :) There will be some failing tasks (due to lack of set secrets) like release and e2e reports uploading, but that's not that important.

**Comment by Haarolean** [comment]
> I still can't make the e2e tests work locally. But I was able to reproduce and fix the exception raised in the smoke tests you run.

oh, thanks much! 😄

**Review by Haarolean — APPROVED** [review]
All workflows seem to be passing successfully on a fork

**Review by germanosin — APPROVED** [review]
Thanks for contribution!

**Comment by sixdouglas** [comment]
Hello @Haarolean 
Rebase should be ok. Local build is so 🤞🏻

**Comment by Haarolean** [comment]
@sixdouglas thank you for your contribution!

**Pull request merged**
